model:
  type: "vit_b"
  checkpoint_url: "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth"
  checkpoint_path: "checkpoints/sam_vit_b_01ec64.pth"

data:
  image_size: 1024
  batch_size: 4
  num_workers: 2
  train_fraction: 0.8
  val_fraction: 0.1
  test_fraction: 0.1

training:
  num_epochs: 20
  learning_rate: 0.001
  seed: 42
  save_interval: 100
  visualize_indices: [9, 18, 27]

paths:
  data_dir: "data"
  image_dir: "data/images"
  mask_dir: "data/masks"
  checkpoint_dir: "checkpoints"
  metrics_log: "logs/metrics_log.csv"
  visualization_dir: "visualizations"

loss:
  dice_weight: 1.0
  boundary_weight: 1.0
  focal_weight: 0.5
  focal_alpha: 0.25
  focal_gamma: 2.0
